Wrap timing logic in its own function. This commit also reduces the volume of messages echoed to the console by default.

diff --git a/bin/CompressAndBuildISO b/bin/CompressAndBuildISO
--- a/bin/CompressAndBuildISO
+++ b/bin/CompressAndBuildISO
@@ -55,6 +55,7 @@ localgit=$root/LocalGit
 packages=$root/Packages
 datadir="$(readlink -f $(dirname $0)/../Data)"
 arch=$(ls $packages/*.bz2 | tail -n1 | sed 's,\(.*\)--\(.*\)--\(.*\).tar.bz2,\3,g')
+unset verbose
 
 if [ "$arch" != "$(uname -m)" ]
 then
@@ -71,6 +72,21 @@ if [ "$usesystemindex" ]
 then filesdir=Data
 else filesdir=Files
 fi
+
+function measure_time() {
+   if [ "$verbose" ]
+   then
+      # Need to do return code hack because time returns 0
+      rtn_file=`mktemp /tmp/BuildLiveCD_return.XXXXXXX`
+      time ("$@"; echo $? >$rtn_file)
+      rtn=`cat $rtn_file`
+      rm -f $rtn_file
+   else
+      "$@"
+      rtn=$?
+   fi
+   return $rtn
+}
 
 function in_rolayer() {
    local rolayer="${root}/Output/ROLayer"
@@ -332,10 +348,10 @@ then
    # compress the uncompressed files into squashfs files
    mkdir -p Output/ISO
    Quiet pushd Output/Environment
-   time mksquashfs_on_demand ../ISO/GoboLinux-files.squashfs $filesdir
+   measure_time mksquashfs_on_demand $root/Output/ISO/GoboLinux-files.squashfs $filesdir
 
    for i in $datadir/Packages-List-*; do 
-      squashfile=../ISO/`basename $i`.squashfs
+      squashfile=$root/Output/ISO/`basename $i`.squashfs
       if [ "$i" -nt "$squashfile" ]
       then
          echo "$i is more recent than $squashfile."
@@ -350,11 +366,9 @@ then
       fi
       searchdirs=`for i in $applist; do echo Programs/$i; done | tr -s '\n' ' '`
 
-      # Conditionally regen squashfs.  Need to do return code hack because time returns 0
-      rtn_file=`mktemp /tmp/BuildLiveCD_return.XXXXXXX`
-      time (mksquashfs_on_demand $squashfile "$searchdirs" "" ""; echo $? >$rtn_file)
-      rtn=`cat $rtn_file`
-      rm -f $rtn_file
+      # Conditionally regen squashfs.
+      measure_time mksquashfs_on_demand $squashfile "$searchdirs" "" ""
+      rtn=$?
 
       # If the squashfs was generated, it contains Packagename dirs rather than Programs/Foo
       # If we append to an existing squashfs -root-becomes allows the root to be reassigned
@@ -366,8 +380,8 @@ then
    done
 
    contents="$(ls --hide="$filesdir" --hide="Programs" --hide="Users" | tr -s '\n' ' ')"
-   time mksquashfs_on_demand ../ISO/GoboLinux-rest.squashfs "$contents" "" "System/Aliens*"
-   time mksquashfs_on_demand ../ISO/GoboLinux-aliens.squashfs "System/Aliens" "" ""
+   measure_time mksquashfs_on_demand $root/Output/ISO/GoboLinux-rest.squashfs "$contents" "" "System/Aliens*"
+   measure_time mksquashfs_on_demand $root/Output/ISO/GoboLinux-aliens.squashfs "System/Aliens" "" ""
    if [ $? == 1 ]
    then
       empty_dir=$(mktemp -d /tmp/BuildLiveCD-emptydir.XXXXX)
@@ -442,7 +456,7 @@ then
    md5sum isolinux/kernel isolinux/initrd *.squashfs >md5sums
    Quiet popd   
    iso_name="Output/GoboLinux-NoVersion.iso"
-   time nice -20 mkisofs -R -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -input-charset utf-8 Output/ISO  > $iso_name
+   measure_time nice -20 mkisofs -R -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -input-charset utf-8 Output/ISO  > $iso_name
    isohybrid_cmd=$(ls TemporaryBuild/syslinux-*/bios/utils/isohybrid | head -n 1)
    $isohybrid_cmd "$iso_name"
    echo "=> ISO stage done"
